db_layout = """

0   REAL_FORMAT.NIVEAU_RUECKLAUF	        REAL		    #
4   REAL_FORMAT.TEMP_RUECKLAUF	            REAL		    #
8   REAL_FORMAT.NIVEAU_VERSORGUNG	        REAL		    #
12  REAL_FORMAT.TEMP_VERSORGUNG	            REAL		    #
16  REAL_FORMAT.RESERVE	                    REAL		    #
20  INT_FORMAT.NIVEAU_RUECKLAUF	            INT             #
22  INT_FORMAT.TEMP_RUECKLAUF	            INT             #
24  INT_FORMAT.NIVEAU_VERSORGUNG	        INT             #
26  INT_FORMAT.TEMP_VERSORGUNG	            INT             #
28  INT_FORMAT.RESERVE	                    INT	            #
30  REAL_FEEDBACK.PRUEFLING_ISTWERT	        REAL            #PRUEFLING SCHWENKWINKEL ISTWERT TST2	
34  REAL_FEEDBACK.VBS_LOADSENSE_ISTWERT	    REAL            #VBS-VENTIL LOADSENSE ISTWERT TST2	
38  REAL_FEEDBACK.RESERVE	                REAL            #	
42  INT_FEEDBACK.PRUEFLING_ISTWERT	        INT	    	    #PRUEFLING SCHWENKWINKEL ISTWERT TST2	
44  INT_FEEDBACK.VBS_LOADSENSE_ISTWERT	    INT	    	    #VBS-VENTIL LOADSENSE ISTWERT TST2	
46  INT_FEEDBACK.RESERVE	                INT	      	    #		
48  REAL_PRESSURE.DRUCK_SAE_A_11KW	        REAL      	    #DRUCK PRUEFLING 11KW SAE A	
52  REAL_PRESSURE.DRUCK_SAE_B_22KW	        REAL    	    #DRUCK PRUEFLING 22KW SAE B	
56  REAL_PRESSURE.DRUCK_SAE_C_37KW	        REAL    	    #DRUCK PRUEFLING 37KW SAE C	
60  REAL_PRESSURE.DRUCK_STRANG_A_TST_2	    REAL    	    #DRUCK PRUEFLING STRANG A	
64  REAL_PRESSURE.LECKAGE_TST2	            REAL    	    #DRUCK PRUEFLING STRANG B	
68  REAL_PRESSURE.DRUCK_STRANG_LS_TST_2	    REAL    	    #DRUCK PRUEFLING STRANG LS	
72  REAL_PRESSURE.DRUCK_STEUEROEL_TST_2	    REAL    	    #DRUCK STEUERL	
76  REAL_PRESSURE.RESERVE	                REAL    	    #	
80  INT_PRESSURE.DRUCK_SAE_A_11KW	        INT 		    #DRUCK PRUEFLING 11KW SAE A	
82  INT_PRESSURE.DRUCK_SAE_B_22KW	        INT 		    #DRUCK PRUEFLING 22KW SAE B	
84  INT_PRESSURE.DRUCK_SAE_C_37KW	        INT 		    #DRUCK PRUEFLING 37KW SAE C	
86  INT_PRESSURE.DRUCK_STRANG_A_TST_2	    INT 		    #DRUCK PRUEFLING STRANG A	
88  INT_PRESSURE.LECKAGE_TST2	            INT 		    #Leckage TST2	
90  INT_PRESSURE.DRUCK_STRANG_LS_TST_2	    INT 		    #DRUCK PRUEFLING STRANG LS	
92  INT_PRESSURE.DRUCK_STEUEROEL_TST_2	    INT 		    #DRUCK STEUEROEL	
94  INT_PRESSURE.auss	                    INT             #
"""

db_layout_output = """

0   DRUCKSOLLWERT_TST2	        INT	    #DB81.DBW0 DRUCKSOLLWERT TST2	
2   SOLLWERTVBS_VENTIL_TST2	    INT 	#DB81.DBW2 VBS-SOLLWERT TST2	
4   SOLLWERT_PRUFLING_TST2	    INT 	#DB81.DBW4 SOLLWERT PRUEFLING TST2	
6   DRUCKSOLL_TST2_UNSCALE	    INT 	#DB81.DBW6 DRUCKSOLLWERT TST2 UNSCALE	
8   DRUCKSOLLWERT_TST2_OUT	    INT 	#DB81.DBW8 DRUCKSOLLWERT TST2	
10  SOLLWERTVBS_VENTIL_TST21	INT 	#DB82.DBW10 VBS-SOLLWERT TST2	
12  SOLLWERT_PRUFLING_TST2_O	INT 	#DB82.DBW12 SOLLWERT PRUEFLING TST2	
14  DRUCKSOLL_TST2_REGLER	    INT	    #0DB81.DBW14 DRUCKSOLLWERT TST2 Regler	
16  OVERLOAD_DRUCK	            INT	    #DB81.DBW16 OVERLOAD DRUCKREGLER	
18  UNDERLOAD_DRUCK	            INT     #DB81.dbw18 UNDERLOAD DRUCKREGLER	
"""